context:
  version: "0.3.14"

package:
  name: gflow
  version: ${{ version }}

source:
  url: https://github.com/AndPuQing/gflow/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2cd3b3802b24491bad18fcd80f8393a39ab31ed54d803d99d75e0dc429dbfe70

build:
  number: 0
  skip:
    - win
    - osx
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - gflowd --version

about:
  homepage: https://github.com/AndPuQing/gflow
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    A lightweight, single-node job scheduler written in Rust.
  summary: "Lightweight GPU Job Scheduler"
  documentation: https://docs.rs/gflow
  repository: https://github.com/AndPuQing/gflow

extra:
  recipe-maintainers:
    - AndPuQing
