context:
  version: "0.4.0"

package:
  name: gflow
  version: ${{ version }}

source:
  url: https://github.com/AndPuQing/gflow/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ed72bf4da80d62645880282b7c1fc26dc7444302e0fd683ee2c222605ffc72b8

build:
  number: 0
  skip:
    - win
    - osx
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - gflowd --version

about:
  homepage: https://github.com/AndPuQing/gflow
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    A lightweight, single-node job scheduler written in Rust.
  summary: "Lightweight GPU Job Scheduler"
  documentation: https://docs.rs/gflow
  repository: https://github.com/AndPuQing/gflow

extra:
  recipe-maintainers:
    - AndPuQing
